#!/bin/bash

# THIS SCRIPT IS INVOKED BY void-installer AS "THE" CHROOT SCRIPT. THE RANDOM
# VARIABLES THAT ARE IN THIS SCRIPT COME FROM THE INVOCANT SCRIPT.

UEFI_UUID=$(blkid -s UUID -o value /dev/sda1)
ROOT_UUID=$(blkid -s UUID -o value /dev/mapper/cryptroot)
awk -i inplace 'en_US-UTF-8 {sub(/^#/,"")}; print' /etc/default/libc-locales
xbps-reconfigure -f glibc-locales
cat <<EOF > /etc/fstab
UUID=$ROOT_UUID / btrfs $BTRFS_OPTS,subvol=@ 0 1
UUID=$UEFI_UUID /boot vfat defaults,noatime 0 2
UUID=$ROOT_UUID /var btrfs $BTRFS_OPTS,subvol=@var 0 2
UUID=$ROOT_UUID /.snapshots btrfs $BTRFS_OPTS,subvol=@snapshots 0 2
tmpfs /tmp tmpfs defaults,nosuid,nodev 0 0
EOF
echo hostonly=yes >> /etc/dracut.conf
xbps-install -Syu void-repo-nonfree
xbps-install -Sy intel-ucode
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id="Void Linux"
xbps-reconfigure -fa
echo root password:
passwd root
